# Generated by Django 3.2.9 on 2022-01-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('wechat_openid', models.CharField(default='', max_length=40)),
                ('user_name', models.CharField(max_length=10)),
                ('user_gender', models.CharField(max_length=5)),
                ('user_dept', models.CharField(max_length=15)),
                ('user_phone', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
