# Generated by Django 4.0.1 on 2022-01-31 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFace',
            fields=[
                ('pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('face_path', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.userinfo')),
            ],
            options={
                'db_table': 'user_face',
            },
        ),
    ]
