# Generated by Django 4.0.1 on 2022-01-31 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_userface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userface',
            old_name='user_id',
            new_name='user',
        ),
    ]
