# Generated by Django 4.0.1 on 2022-01-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_rename_user_id_userface_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userface',
            name='user_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
