# Generated by Django 4.0.1 on 2022-02-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_userface_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userface',
            old_name='user',
            new_name='user_id',
        ),
    ]
