# Generated by Django 4.0.1 on 2022-02-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_rename_user_userface_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
