# Generated by Django 4.0.1 on 2022-02-16 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0005_rename_user_userface_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTime',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('attendance_place', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'attendance_time',
            },
        ),
        migrations.CreateModel(
            name='UserAttendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('attendance_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('attendance_state', models.CharField(max_length=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.userinfo')),
            ],
            options={
                'db_table': 'user_attendance',
            },
        ),
    ]
