# Generated by Django 4.0.1 on 2022-02-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetime',
            name='attendance_coordinate',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
