# Generated by Django 4.0.1 on 2022-02-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancetime_attendance_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetime',
            name='attendance_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancetime',
            name='out_time',
            field=models.CharField(max_length=20),
        ),
    ]
