# Generated by Django 4.0.1 on 2022-02-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancetime_attendance_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='attendance_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='out_time',
            field=models.DateField(),
        ),
    ]
