# Generated by Django 4.0.1 on 2022-02-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_userattendance_attendance_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userattendance',
            old_name='out_time',
            new_name='attendance_date',
        ),
        migrations.AddField(
            model_name='userattendance',
            name='attendance_out_time',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='attendance_time',
            field=models.CharField(max_length=20),
        ),
    ]
