# Generated by Django 4.0.1 on 2022-02-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_rename_out_time_userattendance_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='attendance_state',
            field=models.CharField(default='缺勤', max_length=5),
        ),
    ]
